[package]
name = "breadify"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.36.1"
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
printpdf = { version = "=0.12.6", default-features = false }
rfd = "0.17.2"
thiserror = "2.0.20"
ttf-parser = "0.25.1"

[dev-dependencies]
serde_json = "1.0.151"
ttf-parser = "0.25.1"
